export const data=[
    {
        "Mã khách hàng": "BB 1",
        "Chi nhánh": "256HHH",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "Cô Năm",
        "Điện thoại": "1",
        "Địa chỉ": "QL 1A, Ranh Giới Hồng Liêm, Bắc Bình",
        "Khu vực": "Bình Thuận - Huyện Bắc Bình",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:47",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "chị Tien",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "Tiên",
        "Điện thoại": null,
        "Địa chỉ": null,
        "Khu vực": null,
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": "Nữ",
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Seanest_Lý 0943356976",
        "Ngày tạo": "02:01:2020 21:50:03",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "chú Dương",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "Chú Dương",
        "Điện thoại": null,
        "Địa chỉ": "A6 võ văn kiệt",
        "Khu vực": "Bình Thuận - Thành phố Phan Thiết",
        "Phường xã": "Phường Phú Thủy",
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": "Nam",
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Seanest_Lý 0943356976",
        "Ngày tạo": "29:02:2020 14:01:23",
        "Ngày giao dịch cuối": "29:02:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "Hiếu Thủy",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "Hiếu Thủy",
        "Điện thoại": null,
        "Địa chỉ": "km7",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": "Xã Hàm Chính",
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": "Nữ",
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Seanest_Lý 0943356976",
        "Ngày tạo": "03:02:2020 17:53:21",
        "Ngày giao dịch cuối": "03:02:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HT 1",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TDV Hoa",
        "Điện thoại": "2",
        "Địa chỉ": "QL 1A, Đồi Non, xã Tân Phúc, Hàm Tân, Bình Thuận",
        "Khu vực": "Bình Thuận - Huyện Hàm Tân",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:47",
        "Ngày giao dịch cuối": "14:02:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 1",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Cô Bông",
        "Điện thoại": "0916655844",
        "Địa chỉ": "Thôn Ninh Thuận Hẻm QL 28 Hàm Chính Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:47",
        "Ngày giao dịch cuối": "10:02:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 10",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Dũng Hương",
        "Điện thoại": "0335692428",
        "Địa chỉ": "Thôn Phú Lập Hẻm QL 28 Hàm Phú Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:47",
        "Ngày giao dịch cuối": "02:03:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 100",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "CH Anh Còi",
        "Điện thoại": "0944898976",
        "Địa chỉ": "Chợ Phú Long Tt Phú Long Phú Long Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "17:02:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 101",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Mỹ Linh",
        "Điện thoại": "0919378792",
        "Địa chỉ": "192 Ql 1a Phú Hòa Phú Long Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "22:02:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 102",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Chị Thúy",
        "Điện thoại": "0386486407",
        "Địa chỉ": "Ngã Ba Hàm Trí Km 21 Ql 28 Hàm Trí Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 103",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Th Vui",
        "Điện thoại": "02523865261",
        "Địa chỉ": "Thôn 1 Km21 Ql28 Hàm Trí Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 104",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Hiếu Hải",
        "Điện thoại": "0907559337",
        "Địa chỉ": "Km 26 Ql28 Phú Thái Hàm Trí Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 105",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Cường An",
        "Điện thoại": "0348732208",
        "Địa chỉ": "Km27 Ql28 Phú Thái Hàm Trí Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 106",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Phương Tự",
        "Điện thoại": "02523617106",
        "Địa chỉ": "Km 28 Ql28 Dân Hòa Thuận Hòa Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 107",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Kim Sen",
        "Điện thoại": "0949700212",
        "Địa chỉ": "154 19/4 Tt Ma Lâm Ma Lâm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 108",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "CH Trâm",
        "Điện thoại": "0338313251",
        "Địa chỉ": "Chợ Ma Lâm Tt Ma Lâm Ma Lâm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 109",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "CH Cô Hương",
        "Điện thoại": "0374415634",
        "Địa chỉ": "05 Kp1 Chợ Ma Lâm Ma Lâm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "17:02:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 11",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Huyền Trang",
        "Điện thoại": "0949402636",
        "Địa chỉ": "Thôn Phú Lập Hẻm QL 28 Hàm Phú Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:47",
        "Ngày giao dịch cuối": "02:03:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 110",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Thanh Hoài",
        "Điện thoại": "0946437328",
        "Địa chỉ": "Km10 Quốc Lộ 28 Hàm Chính Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 111",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Anh Ngọc",
        "Điện thoại": "02523865518",
        "Địa chỉ": "Km10 Quốc Lộ 28 Hàm Chính Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 112",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Đăng Thi",
        "Điện thoại": "0941891956",
        "Địa chỉ": "05 Nguyễn Thị Minh Khai Ma Lâm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 113",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Mỹ Hòa",
        "Điện thoại": "02523865370",
        "Địa chỉ": "Km10 Quốc Lộ 28 Hàm Chính Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 114",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Chị Hà",
        "Điện thoại": "0963669813",
        "Địa chỉ": "Thôn 3 Hẻm QL 1A Hồng Sơn Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "13:01:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 115",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Thu Hùng",
        "Điện thoại": "0919528191",
        "Địa chỉ": "374 Ql 1a Phú Thành Phú Long Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 116",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tiến Đạt",
        "Điện thoại": "0933418398",
        "Địa chỉ": "Thôn Kim Bình Hàm Thắng Hàm Thắng Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 117",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Chín Út",
        "Điện thoại": "0945130660",
        "Địa chỉ": "Thôn Kim Bình Hàm Thắng Hàm Thắng Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "22:02:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 118",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Chị Mức",
        "Điện thoại": "0832236372",
        "Địa chỉ": "Hẽm Cá Rô Thắng Thuận Hàm Thắng Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "01:02:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 119",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Xuân",
        "Điện thoại": "0394815516",
        "Địa chỉ": "Km3 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 12",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Hoa",
        "Điện thoại": "0962988958",
        "Địa chỉ": "Chợ Hàm Đức 5 QL 1A Hàm Đức Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:47",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 120",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Xuân Hòa",
        "Điện thoại": "02523838427",
        "Địa chỉ": "Km3 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 121",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Huy Khiêm",
        "Điện thoại": "0919499180",
        "Địa chỉ": "Km3 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 122",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Hoàng Sơn",
        "Điện thoại": "0377951145",
        "Địa chỉ": "Km3 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 123",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Vy Lượng",
        "Điện thoại": "02523838679",
        "Địa chỉ": "Km3 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 124",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Khánh Khuê",
        "Điện thoại": "0946678829",
        "Địa chỉ": "Km3 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 125",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Cô Mai",
        "Điện thoại": "0946477175",
        "Địa chỉ": "Km3 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 126",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Hoàng Oanh",
        "Điện thoại": "0915821251",
        "Địa chỉ": "Km3 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 127",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "CH Tạp Hóa Thông",
        "Điện thoại": "02523833683",
        "Địa chỉ": "Km3 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 128",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Thuận Thảo",
        "Điện thoại": "0902642641",
        "Địa chỉ": "Km5 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 129",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Tạp Hóa Thanh Tuyền",
        "Điện thoại": "0363025339",
        "Địa chỉ": "Km5 Quốc Lộ 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "00:01:1900 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 13",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Thủy Mến",
        "Điện thoại": "0366027014",
        "Địa chỉ": "Thôn 5 QL 1A Hàm Đức Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:47",
        "Ngày giao dịch cuối": "04:01:2020 00:00:00",
        "Trạng thái": 1
    },
    {
        "Mã khách hàng": "HTB 130",
        "Chi nhánh": "Cá nhân",
        "Loại khách hàng": "NPP MAI NGUYỄN",
        "Tên khách hàng": "TH Ái Hoài",
        "Điện thoại": "0979710210",
        "Địa chỉ": "Thôn Thuận Điền Hẻm QL 28 Hàm Liêm Hàm Thuận Bắc",
        "Khu vực": "Bình Thuận - Huyện Hàm Thuận Bắc",
        "Phường xã": null,
        "Công ty": null,
        "Ngày sinh": null,
        "Giới tính": null,
        "Email": null,
        "Nhóm khách hàng": null,
        "Ghi chú": null,
        "Người tạo": "Mainguyen_Thanh 0937058345",
        "Ngày tạo": "31:12:2019 10:32:48",
        "Ngày giao dịch cuối": "24:02:2020 00:00:00",
        "Trạng thái": 1
    }
]
CREATE TABLE filterproducts (`iduser` varchar(20) PRIMARY KEY,`Loại hàng` INT(2),`Loại thực đơn` INT(2),`Nhóm hàng` INT(2),`Mã hàng hóa` INT(2),`Tên hàng hóa` INT(2),`Giá vốn` INT(2),`Giá bán` INT(2),`Tồn kho` INT(2),`Đặt hàng` INT(2),`Tồn nhỏ nhất` INT(2),`Tồn lớn nhất` INT(2),`Mã ĐVT Cơ bản` INT(2),`Quy đổi` INT(2),`Mã HH Liên quan` INT(2),`ĐVT` INT(2),`Trọng lượng` INT(2),`Trạng thái` INT(2),`Ghi chú` INT(2))
CREATE TABLE products (`iduser` varchar(20) PRIMARY KEY,`Loại hàng` VARCHAR(100),`Loại thực đơn` VARCHAR(100),`Nhóm hàng` VARCHAR(100),`Mã hàng hóa` VARCHAR(100),`Tên hàng hóa` VARCHAR(100),`Giá vốn` VARCHAR(100),`Giá bán` VARCHAR(100),`Tồn kho` VARCHAR(100),`Đặt hàng` VARCHAR(100),`Tồn nhỏ nhất` VARCHAR(100),`Tồn lớn nhất` VARCHAR(100),`Mã ĐVT Cơ bản` VARCHAR(100),`Quy đổi` VARCHAR(100),`Mã HH Liên quan` VARCHAR(100),`ĐVT` VARCHAR(100),`Trọng lượng` VARCHAR(100),`Trạng thái` VARCHAR(100),`Ghi chú` VARCHAR(100))
CREATE TABLE filtercustomer (`Mã khách hàng` INT(2),`Chi nhánh` INT(2),`Loại khách hàng` INT(2),`Tên khách hàng` INT(2),`Điện thoại` INT(2),`Địa chỉ` INT(2),`khu vực` INT(2),`Phường xã` INT(2),`Công ty` INT(2),`Ngày sinh` INT(2),`Giới tính` INT(2),`email` INT(2),`Nhóm khách hàng` INT(2),`Ghi chú` INT(2),`Người tạo` INT(2),`Ngày tạo` INT(2),`Ngày giao dịch cuối` INT(2),`Trạng thái` INT(2),`iduser` varchar(20) PRIMARY KEY)
CREATE TABLE filtercustomer (`Mã khách hàng` VARCHAR(100) PRIMARY KEY,`Chi nhánh` VARCHAR(100),`Loại khách hàng` VARCHAR(100),`Tên khách hàng` VARCHAR(100),`Điện thoại` VARCHAR(100),`Địa chỉ` VARCHAR(100),`khu vực` VARCHAR(100),`Phường xã` VARCHAR(100),`Công ty` VARCHAR(100),`Ngày sinh` VARCHAR(100),`Giới tính` VARCHAR(100),`email` VARCHAR(100),`Nhóm khách hàng` VARCHAR(100),`Ghi chú` VARCHAR(100),`Người tạo` VARCHAR(100),`Ngày tạo` VARCHAR(100),`Ngày giao dịch cuối` VARCHAR(100),`Trạng thái` VARCHAR(100))
CREATE TABLE datatraphaco (`stt` VARCHAR(100) PRIMARY KEY,`Vùng` VARCHAR(100),`Khu vực` VARCHAR(100),`Địa bàn` VARCHAR(100),`Chi nhánh đới tác` VARCHAR(100),`Mã khách hàng` VARCHAR(100),`Mã hợp đồng` VARCHAR(100),`Mã hệ thống` VARCHAR(100),`Đon vị` VARCHAR(100),`Mã trình dược viên` VARCHAR(100),`Tên trình dược viên` VARCHAR(100),`Mã vật tư` VARCHAR(100),`Tên vật tư` VARCHAR(100),`ĐVT` VARCHAR(100),`Số lượng` VARCHAR(100),`Đơn giá` VARCHAR(100),`Danh thu` VARCHAR(100),`Thuế GTGT` VARCHAR(100),`Tỏng tiền` varchar(20))
datatraphaco
`Vùng`=?,`Chi nhánh đới tác`=?,`Mã khách hàng`=?,`Mã hợp đồng`=?,`Mã hệ thống`=?,`Đon vị`=?,`Mã trình dược viên`=?,`Tên trình dược viên`=?,`Mã vật tư`=?,`Tên vật tư`=?,`ĐVT`=?,`Số lượng`=?,`Đơn giá`=?,`Danh thu`=?,`Thuế GTGT`=?,`Tỏng tiền`=?,`Khu vực`=?,`Địa bàn`=?
`Vung`=?,`Khu_vuc`=?,`Dia_ban`=?,`Chi_nhanh_doi_tac`=?,`Ma_khach_hang`=?,`Ma_hop_dong`=?,`Ma_he_thong`=?,`Don_vi`=?,`Ma_trinh_dc_vien`=?,`Ten_trinh_duoc_vien`=?,`Ma_vat_tu`=?,`Ten_vat_tu`=?,`Dvt`=?,`So_luong`=?,`Don_gia`=?,`Doanh_thu`=?,`Thue_GTGT`=?,`Tong_tien`=? where `Stt`=?
`Vung` VARCHAR(100),`Khu_vuc` VARCHAR(100),`Dia_ban` VARCHAR(100),`Chi_nhanh_doi_tac` VARCHAR(100),`Ma_khach_hang` VARCHAR(100),`Ma_hop_dong` VARCHAR(100),`Ma_he_thong` VARCHAR(100),`Don_vi` VARCHAR(100),`Ma_trinh_dc_vien` VARCHAR(100),`Ten_trinh_duoc_vien` VARCHAR(100),`Ma_vat_tu` VARCHAR(100),`Ten_vat_tu` VARCHAR(100),`Dvt` VARCHAR(100),`So_luong` VARCHAR(100),`Don_gia` VARCHAR(100),`Doanh_thu` VARCHAR(100),`Thue_GTGT` VARCHAR(100),`Tong_tien` VARCHAR(100) where `Stt` VARCHAR(100)
`Loại hàng` `Nhóm hàng` `Mã hàng hóa` `Tên hàng hóa` `Ngày nhập kho` `Hạn sử dụng` `Giá vốn` `Giá bán` `Tồn kho` `Đặt hàng` `Mã ĐVT Cơ bản` `Quy đổi` `Mã HH Liên quan` `ĐVT` `Trọng lượng` `Trạng thái` `Ghi chú`